CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE IF NOT EXISTS region (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE IF NOT EXISTS properties (
    id INTEGER NOT NULL PRIMARY KEY,
    address_string TEXT NOT NULL,
    FOREIGN KEY (region_id) REFERENCES region(id),
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)


CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER NOT NULL PRIMARY KEY,
    text TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (property_id) REFERENCES properties(id),
)
